export enum ActionType {
  FETCH_DATA = "FETCH_DATA", // START TO GET FETCH DATA
  ON_LOADING = "ON_LOADING", //LOADING: TRUE
  STORE_DATA = "STORE_DATA", // STORE_DATA FROM AXIOS GET
  END_LOADING = "END_LOADING", //LOADING: FALSE
}
